apiVersion: v1
kind: Pod
metadata:
  name: redis01
  namespace: microservice-demo
spec:
  containers:
  - name: redis01
    image: redis:3
    ports:
    - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis01
  namespace: microservice-demo
spec:
  selector:
    app: redis01
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379