apiVersion: apps/v1
kind: Deployment
metadata:
  name: results-app
  namespace: microservice-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: results-app
  template:
    metadata:
      labels:
        app: results-app
    spec:
      containers:
      - name: results-app
        image: muhakmalfadh/microservice-demo-reults-app:latest
        ports:
        - containerPort: 80
        env:
        - name: REDIS_HOST
          value: "redis01.microservice-demo.svc.cluster.local"
        - name: DATABASE_HOST
          value: "store-service.microservice-demo.svc.cluster.local"
---
apiVersion: v1
kind: Service
metadata:
  name: results-app
  namespace: microservice-demo
spec:
  type: NodePort
  selector:
    app: results-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
