apiVersion: v1
kind: Pod
metadata:
  name: store
  namespace: microservice-demo
spec:
  containers:
  - name: store
    image: postgres:9.5
    env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: pg8675309
