apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-worker
  namespace: microservice-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-worker
  template:
    metadata:
      labels:
        app: vote-worker
    spec:
      containers:
      - name: vote-worker
        image: muhakmalfadh/microservice-demo-vote-worker:latest
        env:
        - name: FROM_REDIS_HOST
          value: "1"
        - name: TO_REDIS_HOST
          value: "1"
        - name: REDIS_HOST
          value: "redis01.microservice-demo.svc.cluster.local"
        - name: DATABASE_HOST
          value: "store-service.microservice-demo.svc.cluster.local"
