apiVersion: v1
kind: Service
metadata:
  name: web-vote-app
  namespace: microservice-demo
spec:
  type: NodePort
  selector:
    app: web-vote-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
