apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-vote-app
  namespace: microservice-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-vote-app
  template:
    metadata:
      labels:
        app: web-vote-app
    spec:
      containers:
      - name: web-vote-app
        image: muhakmalfadh/microservice-demo-web-vote-app:latest
        ports:
        - containerPort: 80
        env:
        - name: WEB_VOTE_NUMBER
          value: "01"
---
apiVersion: v1
kind: Service
metadata:
  name: web-vote-app
spec:
  selector:
    app: web-vote-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80